name = "BetaZero"
uuid = "c2a2f090-4363-4bef-a985-c7cb903c4681"
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
D3Trees = "e3df1716-f71e-5df9-9e2d-98e193103c45"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LightDark = "a1c7e911-b2d9-4cdc-ae72-88f9232b4333"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
MinEx = "5e646c51-9649-468d-a822-1bc45f963efc"
MineralExploration = "8a34a384-1fed-11ec-9621-0242ac130002"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
POMDPGifs = "7f35509c-0cb9-11e9-0708-2928828cdbb7"
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ParticleBeliefs = "aa14124c-3bd6-4f21-947b-abce5ea6e230"
ParticleFilters = "c8b314e2-9260-5cf8-ae76-3be7461ca6d0"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reel = "71555da5-176e-5e73-a222-aebc6c6e4f2f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RemoteJobs = "3bc6ca60-8b85-4286-b881-d4609ff8527d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
